export const bank_options = [
  { value: "Vietcombank", label: "Vietcombank" },
  { value: "VietinBank", label: "VietinBank" },
  { value: "BIDV", label: "BIDV" },
  { value: "Agribank", label: "Agribank" },
  { value: "Techcombank", label: "Techcombank" },
  { value: "ACB", label: "ACB" },
  { value: "MB Bank", label: "MB Bank" },
  { value: "Sacombank", label: "Sacombank" },
  { value: "TPBank", label: "TPBank" },
  { value: "VPBank", label: "VPBank" },
  { value: "SHB", label: "SHB" },
  { value: "HDBank", label: "HDBank" },
  { value: "SeABank", label: "SeABank" },
  { value: "VIB", label: "VIB" },
  { value: "Eximbank", label: "Eximbank" },
  { value: "SCB", label: "SCB" },
  { value: "OCB", label: "OCB" },
  { value: "LienVietPostBank", label: "LienVietPostBank" },
  { value: "MSB", label: "MSB" },
  { value: "Nam A Bank", label: "Nam A Bank" },
  { value: "ABBANK", label: "ABBANK" },
  { value: "PVcomBank", label: "PVcomBank" },
  { value: "Bac A Bank", label: "Bac A Bank" },
  { value: "NCB", label: "NCB" },
  { value: "VietABank", label: "VietABank" },
  { value: "VietBank", label: "VietBank" },
  { value: "BaoViet Bank", label: "BaoViet Bank" },
  { value: "SAIGONBANK", label: "SAIGONBANK" },
  { value: "Co-opBank", label: "Co-opBank" },
  { value: "GPBank", label: "GPBank" },
  { value: "VRB", label: "VRB" },
  { value: "PGBank", label: "PGBank" },
  { value: "Kienlongbank", label: "Kienlongbank" },
  { value: "HLBVN", label: "HLBVN" },
  { value: "UOB", label: "UOB" },
  { value: "HSBC", label: "HSBC" },
  { value: "Standard Chartered", label: "Standard Chartered" },
  { value: "Shinhan Bank", label: "Shinhan Bank" },
  { value: "Public Bank", label: "Public Bank" },
  { value: "ANZ", label: "ANZ" },
  { value: "CIMB", label: "CIMB" },
  { value: "Indovina Bank", label: "Indovina Bank" },
  { value: "Woori Bank", label: "Woori Bank" },
  { value: "VDB", label: "VDB" },
  { value: "VBSP", label: "VBSP" },
  { value: "Khác", label: "Khác" },
];

export const bank_bin_map: Record<string, string> = {
  Vietcombank: "970436",
  VietinBank: "970415",
  BIDV: "970418",
  Agribank: "970405",

  Techcombank: "970407",
  ACB: "970416",
  "MB Bank": "970422",
  Sacombank: "970403",
  TPBank: "970423",
  VPBank: "970432",
  SHB: "970443",
  HDBank: "970437",
  SeABank: "970440",
  VIB: "970441",
  Eximbank: "970431",
  SCB: "970429",
  OCB: "970448",

  LienVietPostBank: "970449",
  MSB: "970426",
  "Nam A Bank": "970428",
  ABBANK: "970425",
  PVcomBank: "970412",
  "Bac A Bank": "970409",
  NCB: "970419",
  VietABank: "970427",
  VietBank: "970433",
  "BaoViet Bank": "970438",
  SAIGONBANK: "970400",
  "Co-opBank": "970446",
  GPBank: "970408",
  VRB: "970421",
  PGBank: "970430",
  Kienlongbank: "970452",

  HLBVN: "970442", // Hong Leong
  UOB: "970458",
  HSBC: "458761",
  "Standard Chartered": "970410",
  "Shinhan Bank": "970424",
  "Public Bank": "970439",
  ANZ: "970406",
  CIMB: "970454",
  "Indovina Bank": "970434",
  "Woori Bank": "970457",

  VDB: "970406", // Vietnam Development Bank (ít dùng QR)
  VBSP: "999888", // Ngân hàng CSXH (không hỗ trợ VietQR chuẩn)
};
