export const language_options = [
  { label: "English", value: "English" },
  { label: "中文 (Chinese)", value: "中文 (Chinese)" },
  { label: "Español (Spanish)", value: "Español (Spanish)" },
  { label: "Français (French)", value: "Français (French)" },
  { label: "العربية (Arabic)", value: "العربية (Arabic)" },
  { label: "Português (Portuguese)", value: "Português (Portuguese)" },
  { label: "Русский (Russian)", value: "Русский (Russian)" },
  { label: "Deutsch (German)", value: "Deutsch (German)" },
  { label: "हिन्दी (Hindi)", value: "हिन्दी (Hindi)" },
  { label: "বাংলা (Bengali)", value: "বাংলা (Bengali)" },
  { label: "日本語 (Japanese)", value: "日本語 (Japanese)" },
  { label: "한국어 (Korean)", value: "한국어 (Korean)" },
  { label: "Tiếng Việt", value: "Tiếng Việt" },
  { label: "ภาษาไทย (Thai)", value: "ภาษาไทย (Thai)" },
  { label: "Italiano (Italian)", value: "Italiano (Italian)" },
  { label: "Türkçe (Turkish)", value: "Türkçe (Turkish)" },
  { label: "Nederlands (Dutch)", value: "Nederlands (Dutch)" },
  { label: "Other", value: "Other" },
];
