export const ethnicityOptions = [
  { value: "Kinh", label: "Kinh" },
  { value: "Tày", label: "Tày" },
  { value: "Thái", label: "Thái" },
  { value: "Mường", label: "Mường" },
  { value: "Hoa", label: "Hoa" },
  { value: "Khơ-me", label: "Khơ-me" },
  { value: "Nùng", label: "Nùng" },
  { value: "HMông", label: "HMông" },
  { value: "Dao", label: "Dao" },
  { value: "Gia-rai", label: "Gia-rai" },
  { value: "Ê-đê", label: "Ê-đê" },
  { value: "Ba-na", label: "Ba-na" },
  { value: "Sán Chay", label: "Sán Chay" },
  { value: "Chăm", label: "Chăm" },
  { value: "Xơ-đăng", label: "Xơ-đăng" },
  { value: "Sán Dìu", label: "Sán Dìu" },
  { value: "Hrê", label: "Hrê" },
  { value: "Cơ-ho", label: "Cơ-ho" },
  { value: "Ra-glai", label: "Ra-glai" },
  { value: "Mnông", label: "Mnông" },
  { value: "Thổ", label: "Thổ" },
  { value: "Xtiêng", label: "Xtiêng" },
  { value: "Khơmú", label: "Khơmú" },
  { value: "Bru-Vân Kiều", label: "Bru-Vân Kiều" },
  { value: "Giáy", label: "Giáy" },
  { value: "Cơ-tu", label: "Cơ-tu" },
  { value: "Gié-Triêng", label: "Gié-Triêng" },
  { value: "Ta-ôi", label: "Ta-ôi" },
  { value: "Mạ", label: "Mạ" },
  { value: "Co", label: "Co" },
  { value: "Chơ-ro", label: "Chơ-ro" },
  { value: "Hà Nhì", label: "Hà Nhì" },
  { value: "Xinh-mun", label: "Xinh-mun" },
  { value: "Chu-ru", label: "Chu-ru" },
  { value: "Lào", label: "Lào" },
  { value: "La-chí", label: "La-chí" },
  { value: "Phù Lá", label: "Phù Lá" },
  { value: "La Hủ", label: "La Hủ" },
  { value: "Kháng", label: "Kháng" },
  { value: "Lự", label: "Lự" },
  { value: "Pà Thẻn", label: "Pà Thẻn" },
  { value: "LôLô", label: "LôLô" },
  { value: "Chứt", label: "Chứt" },
  { value: "Mảng", label: "Mảng" },
  { value: "Cờ lao", label: "Cờ lao" },
  { value: "Bố Y", label: "Bố Y" },
  { value: "La Ha", label: "La Ha" },
  { value: "Cống", label: "Cống" },
  { value: "Ngái", label: "Ngái" },
  { value: "Si La", label: "Si La" },
  { value: "Pu Péo", label: "Pu Péo" },
  { value: "Brâu", label: "Brâu" },
  { value: "Rơ-măm", label: "Rơ-măm" },
  { value: "Ơ-đu", label: "Ơ-đu" },
];
